{"created": 1744671636.063513, "duration": 0.05847001075744629, "exitcode": 2, "root": "/Users/ray/Desktop/GITHUB/Novamind-Backend-ONLY-TWINS/backend", "environment": {}, "summary": {"total": 0, "collected": 0}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "app/tests/security/phi/test_phi_audit_logic.py", "type": "Module"}]}, {"nodeid": "app/tests/security/phi/test_phi_audit_logic.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module '/Users/ray/Desktop/GITHUB/Novamind-Backend-ONLY-TWINS/backend/app/tests/security/phi/test_phi_audit_logic.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nphi/test_phi_audit_logic.py:18: in <module>\n    from scripts.run_hipaa_phi_audit import PHIAuditor, PHIAuditResult\nE   ModuleNotFoundError: No module named 'scripts.run_hipaa_phi_audit'"}], "tests": []}